# Generated by Django 4.2.2 on 2023-07-01 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="redactor",
            options={
                "ordering": ["id"],
                "verbose_name": "redactor",
                "verbose_name_plural": "redactors",
            },
        ),
    ]
