# Generated by Django 4.2.2 on 2023-07-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper", "0002_alter_redactor_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(default="0", max_length=2),
        ),
    ]
