# Generated by Django 4.2.2 on 2023-07-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper", "0003_alter_redactor_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(default="0"),
        ),
    ]
