# Generated by Django 4.2.2 on 2023-09-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper", "0005_alter_newspaper_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(default=0),
        ),
    ]
